# Generated by Django 3.0.6 on 2020-10-29 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201029_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_profile',
        ),
        migrations.DeleteModel(
            name='user_profile',
        ),
    ]
