# Generated by Django 3.0.6 on 2020-10-13 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0003_auto_20201013_0746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestiside',
            name='disease',
        ),
        migrations.AddField(
            model_name='disease',
            name='pestiside',
            field=models.ManyToManyField(to='diagnose.Pestiside'),
        ),
    ]
