# Generated by Django 3.0.6 on 2020-10-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0004_auto_20201013_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disease',
            name='pestiside',
        ),
        migrations.AddField(
            model_name='pestiside',
            name='disease',
            field=models.ManyToManyField(to='diagnose.Disease'),
        ),
    ]
