# Generated by Django 3.0.6 on 2020-10-19 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0006_imagemodel_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagemodel',
            name='imagefile',
            field=models.ImageField(null=True, upload_to='images/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='result',
            field=models.CharField(choices=[('tomato early blight', 'tomato early blight'), ('tomato_leaf_blast', 'tomato_leaf_blast'), ('tomato_Leaf_Mold', 'tomato_Leaf_Mold'), ('tomato_Target_Spot', 'tomato_Target_Spot')], default='tomato early blight', max_length=100),
        ),
    ]
