# Generated by Django 3.0.6 on 2020-10-20 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0009_auto_20201020_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='review',
            new_name='comment',
        ),
    ]
