# Generated by Django 3.0.6 on 2020-10-20 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0012_auto_20201020_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='user',
            new_name='author',
        ),
    ]
