# Generated by Django 3.0.6 on 2020-10-28 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0013_auto_20201020_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='pestiside',
            name='imagefile',
            field=models.ImageField(null=True, upload_to='pestisides/', verbose_name=''),
        ),
        migrations.AddField(
            model_name='prediction',
            name='imagefile',
            field=models.ImageField(null=True, upload_to='prediction/', verbose_name=''),
        ),
        migrations.AlterField(
            model_name='imagemodel',
            name='imagefile',
            field=models.ImageField(null=True, upload_to='pestisides/', verbose_name=''),
        ),
    ]
