# Generated by Django 3.0.6 on 2020-10-28 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0014_auto_20201028_0310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestiside',
            name='imagefile',
        ),
        migrations.RemoveField(
            model_name='prediction',
            name='imagefile',
        ),
        migrations.AddField(
            model_name='prediction',
            name='image',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='diagnose.ImageModel'),
            preserve_default=False,
        ),
    ]
