# Generated by Django 3.0.6 on 2020-10-29 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('diagnose', '0021_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_profile',
            name='imagefile',
            field=models.ImageField(default='user.png', upload_to='profile/'),
        ),
        migrations.AlterField(
            model_name='user_profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
