# Generated by Django 3.0.6 on 2020-10-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0022_auto_20201029_1045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_profile',
        ),
    ]
