# Generated by Django 3.0.6 on 2020-11-06 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0028_auto_20201106_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='disease',
            name='symptoms',
            field=models.CharField(default=1, max_length=50000),
        ),
    ]
