# Generated by Django 3.0.6 on 2020-11-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0029_disease_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='symptoms',
            field=models.CharField(default='symptom1.symptom2', max_length=50000),
        ),
    ]
