# Generated by Django 3.0.6 on 2020-11-06 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0031_auto_20201106_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pestiside',
            name='imagefile',
            field=models.ImageField(null=True, upload_to='pestiside/', verbose_name=''),
        ),
    ]
