# Generated by Django 3.0.6 on 2020-11-10 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0032_auto_20201106_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='disease',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='diagnose.Disease'),
        ),
        migrations.AddField(
            model_name='review',
            name='pestiside',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='diagnose.Pestiside'),
        ),
    ]
