# Generated by Django 3.0.6 on 2020-11-10 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0033_auto_20201110_0927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='disease',
            new_name='dis',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='pestiside',
            new_name='pes',
        ),
    ]
