# Generated by Django 3.0.6 on 2020-11-19 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0035_review_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='dis',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, to='diagnose.Disease'),
        ),
        migrations.AlterField(
            model_name='review',
            name='pes',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.CASCADE, to='diagnose.Pestiside'),
        ),
    ]
