# Generated by Django 3.0.6 on 2020-11-23 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0038_remove_review_dis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestiside',
            name='disease',
        ),
        migrations.AddField(
            model_name='pestiside',
            name='disease',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='diagnose.Disease'),
        ),
    ]
