# Generated by Django 3.0.6 on 2020-11-23 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnose', '0039_auto_20201123_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pestiside',
            name='disease',
        ),
        migrations.AddField(
            model_name='pestiside',
            name='disease',
            field=models.ManyToManyField(to='diagnose.Disease'),
        ),
    ]
